### PR TITLE
Update Czech translation

### PR DESCRIPTION
**Pull request by panther7**

### CODE REVIEW

**Comment by martinet101** [comment]
This PR appears as draft... Is it meant to be a draft or it is an error?

**Comment by panther7** [comment]
Draft is correct, these changes are low-prio and waits for "huge" texts.

**Comment by martinet101** [comment]
All right then

**Comment by panther7** [comment]
Done, btw, string "Ok" is duplicate on line 28 and 34.

@martinet101

**Comment by martinet101** [comment]
> 2\. possible wait (example 24 hours) to update translations for latest releases, because now, new releases are not translated

Well, i am studying a dynamic system for the languages (like thay can be downloaded and updated without app restart needed), as well as integration with stuff like poeditor, etc.

**Review by martinet101 — APPROVED** [review]

**Pull request merged**
