### PR TITLE
Chat

### PR DESCRIPTION
**Pull request by panther7**
Only chat with @martinet101 :)

### CODE REVIEW

**Comment by panther7** [comment]
Could you add me to sk translation on Toglee?

**Comment by martinet101** [comment]
I changed your permissions, you should now be able to translate it also

**Comment by panther7** [comment]
Suggest: Add translation done percentage to language selector, like Factorio.

**Comment by panther7** [comment]
"200 chars" error was fixed, but suggest from Tolgee team is, dont use "full" language as key.

**Pull request closed without merging**
