### PR TITLE
Update Czech translation to v3.5.0

### PR DESCRIPTION
**Pull request by panther7**

### CODE REVIEW

**Comment by martinet101** [comment]
New strings available

**Comment by panther7** [comment]
Suggestion: Plural rules for translation hours/minutes, nice example from JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules#using_options

@martinet101

**Comment by martinet101** [comment]
Although it is a good idea, implementing this ia hard, because not all languages use plurals, genders and other flexions in the same way; and for the small places where thi would be used I guess it is not worth the time.

Anyway, thanks for the suggestion, i appreciate them a lot :)

**Comment by panther7** [comment]
JavaScript base "PluralRules" supports "all" languages :).

Python probably not.

**Comment by panther7** [comment]
"Placeholder text"?




@martinet101

**Comment by panther7** [comment]
Missing "secs" translation

**Comment by martinet101** [comment]
> Missing "secs" translation

This was for testing and i'm going to remove it before releasing

**Comment by martinet101** [comment]
> "Placeholder text"?

It shouldn't be like that... are you opening this from any clock or from the tray icon?

**Comment by panther7** [comment]
Help string is not used

**Comment by panther7** [comment]
> > "Placeholder text"?
> 
> It shouldn't be like that... are you opening this from any clock or from the tray icon?

From system tray

**Comment by martinet101** [comment]
> Help string is not used

When I publish the language files there are some features/text that are still being worked on and haven't been pushed yet, but they'll come :)




> Suggestion for fix: Disable (or hide) "Monitor tools" if i have only one monitor, typically on laptop

Yes, seems like a good idea

**Review by martinet101 — APPROVED** [review]

**Pull request merged**
