### PR TITLE
Update Czech translation to v3.2.0

### PR DESCRIPTION
**Pull request by panther7**

### CODE REVIEW

**Review by martinet101 — APPROVED** [review]

**Comment by martinet101** [comment]
New language files are available (v3.2)

**Comment by panther7** [comment]
* "Move to the left" is not use.
* "Check only the focused window on the fullscreen check" what is this feature?

**Review by martinet101 — APPROVED** [review]

**Comment by panther7** [comment]
> * "Move to the left" is not use.
> * "Check only the focused window on the fullscreen check" what is this feature?

@martinet101

**Comment by martinet101** [comment]
_Move to the left_ I think it is used, but i'll take a look.

_Check only the focused window on the fullscreen check_ refers to a testing feature that checks only the focused window instead of all the visible windows when checking if there's anyy fullscreened window

**Pull request merged**
