### PR TITLE
Remove install dateutil via easy_install

### PR DESCRIPTION
**Pull request by panther7**
I think, that is not necessary: https://github.com/martinet101/ElevenClock/commit/3137aaf1c0cae81067b03f3ca04634329c97ec1e#r75552375

### CODE REVIEW

**Comment by panther7** [comment]
run build.bat with these lines has  failed

**Comment by martinet101** [comment]
For me it has worked. 

In fact, it has no reason to fail

**Comment by martinet101** [comment]
Yes, for whatever the reason dateutil does not work if it's not installed by easy_install.

**Comment by panther7** [comment]
But its work without these lines (for me).

**Comment by martinet101** [comment]
Yes, building works, but hte datetime module returns  empty datetime instances, making the tool tip report wrong timezones when additional clocks are specified.

**Comment by panther7** [comment]
Proble is, that easy_install needs admin rights...

````
C:\Users\filip\Documents\git\ElevenClock>python -m easy_install python-dateutil
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\Python310\\Lib\\site-packages\\test-easy-install-20496.write-test'
```

**Comment by panther7** [comment]
And pip is better, that does not require admin rights. :-/

**Comment by martinet101** [comment]
Yes, but when building a python script with PyInstaller and dateutil as a library installed from pip the datetime library returns None instead of timezone objects. If, instead, this is done through easy_install, it works.

**Pull request closed without merging**
