### PR TITLE
Publish releases to Windows Package Manager (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @martinet101.

### CODE REVIEW

**Comment by martinet101** [comment]
It is a really great tool, but winget does automatically update gitub-released apps. 

They have automatically a bot that searches for new releases, and to be honest, the latest version I manually uploaded was 1.5 (if i recall correctly), and now version 3.6.4 is available:
image

Anyway, lots of thanks for the idea!

**Comment by vedantmgoyal2009** [comment]
It is a project called winget-pkgs-automation, which is also maintained by me. But due to the huge number of packages, the GitHub's API rate limit gets exceeded, hence I'm migrating GitHub packages to my action so that software developers are able to manage their releases in winget themselves and the non-GitHub packages are updated efficiently.

**Comment by martinet101** [comment]
Ah ok, I see. Then i'll definitely merge that

**Comment by sitiom** [comment]
@vedantmgoyal2009 The workflow run failed https://github.com/martinet101/ElevenClock/runs/7616683672

**Comment by vedantmgoyal2009** [comment]
The issue should be fixed now. Sorry for the trouble 🙏🏻

**Comment by martinet101** [comment]
Hi @vedantmgoyal2009, thanks for your work!

However, while the action successfully finished, slogs show the following:
image

Was this expected?

**Comment by vedantmgoyal2009** [comment]
You need to update your fork manually or enable the `workflow` scope in your Personal Access Token since the action tries to update workflows under `.github` directory.

**Comment by martinet101** [comment]
Now it works! Thank you :)

**Pull request merged**
