### PR TITLE
Update lang_ko.json

### PR DESCRIPTION
**Pull request by VenusGirl**

### CODE REVIEW

**Comment by martinet101** [comment]
Hi @VenusGirl, the translation program has changed and the translations are done via tolgee, a localization platform.

You can get more details in ElevenClock Wiki.

I'm sorry but this PR can't be merger since changes would get erased when syncing with tolgee.

**Comment by VenusGirl** [comment]
Email registered with Tolgee: Venusgirl@outlook.com
Language to translate: Korean (Ko)

**Comment by martinet101** [comment]
You should now have recieved an e-mail

**Comment by VenusGirl** [comment]
Eleven Clock's project does not appear on Tolgee's dashboard.

**Comment by martinet101** [comment]
You should have received an email (check spam) with an invitation from
tolgee

El dg., 12 de juny 2022, 6:43, VenusGirl❤ ***@***.***> va
escriure:

**Comment by martinet101** [comment]
Hi @VenusGirl, i'll try to import the .json file you translated to Tolgee, so you don't have to rewrite all changes again.

**Comment by VenusGirl** [comment]
Hello,
the mail you used for registration and the languages
***@***.******@***.***>  Korean (ko)



✧₊⁎˓  VᴇɴᴜsGɪʀʟ💋비너스걸💗 ˒⁎⁺˳✧༚
        Now at this moment, my beauty shines the most


보낸 사람: Martí ***@***.***>
보낸 날짜: 2022년 6월 11일 토요일 오전 4:43
받는 사람: ***@***.***>
참조: ***@***.***>; ***@***.***>
제목: Re: [martinet101/ElevenClock] Update lang_ko.json (PR #802)


Hi @VenusGirl<https://github.com/VenusGirl>, the translation program has changed and the translations are done via tolgee, a localization platform.

You can get more details in ElevenClock Wiki.

I'm sorry but this PR can't be merger since changes would get erased when syncing with tolgee.

**Comment by martinet101** [comment]
Hi, i don't understand your message

**Comment by VenusGirl** [comment]
I think it was sent by mistake.

**Pull request closed without merging**
