### PR TITLE
"Last" Czech translation commit

### PR DESCRIPTION
**Pull request by panther7**
Last word in "Nápověda" is splited.

### CODE REVIEW

**Comment by martinet101** [comment]
Fixed!

**Comment by panther7** [comment]
Czech plural for May is "1. května", but Eleven showing "1. květen",



Tooltip on original clock is correct.

**Comment by martinet101** [comment]
Mhmm, that must be an issue with datetime strftime python function... Can you open a separate issue, please?

**Comment by panther7** [comment]
> Mhmm, that must be an issue with datetime strftime python function... Can you open a separate issue, please?

I'm lazy :D ...this MR is best for trasnlation issues :)

**Comment by panther7** [comment]
Is "Disable blurry background" correct?  
Because, is it UNchecked, than is not blurry, and it is checked, is not blurry too.

If custom background is not set, then backgroud is transparent...







All in Windows 11 2H22 (22610.1)

**Comment by martinet101** [comment]
Yes the background color overlays the blurry background. It is meant to be like this

**Review by martinet101 — APPROVED** [review]

**Pull request merged**
