### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by Seeloewen**
Updated the German translation to include the new strings from v3.0.0

### CODE REVIEW

**Review by martinet101 — APPROVED** [review]

**Comment by martinet101** [comment]
Hey @Seeloewen, could you please translate also lang_3_1? i added it to your branch

**Comment by Seeloewen** [comment]
Yeah, I'll translate that too in a moment

**Comment by Seeloewen** [comment]
@martinet101 Done, added new strings and fixed some typos

**Comment by martinet101** [comment]
Thank you :)

**Pull request merged**
