### PR TITLE
Update lang_sample.py

### PR DESCRIPTION
**Pull request by MatousAdamu**
I donť corectly understand some parts:
"Fix the hyphen/dash showing over the month"

### CODE REVIEW

**Comment by martinet101** [comment]
Hey, 

Thank you for the translation, but could you please rename lang_sample.py to lang_[YOUR_LANG_CODE].py?

Thanks :)

**Comment by MatousAdamu** [comment]
Done

**Review by martinet101 — APPROVED** [review]

**Comment by Cvolton** [comment]
this translation is missing the {0} things meant to be filled in by the program itself

**Comment by martinet101** [comment]
You're right, i'll change that

**Comment by martinet101** [comment]
@MatousAdamu, could you please update the missing translations in https://github.com/martinet101/ElevenClock/blob/main/elevenclock/lang/lang_cs.py following the "{0}" standard? (+ info in https://github.com/martinet101/ElevenClock/blob/main/TRANSLATION.md)

Thanks :)

**Comment by MatousAdamu** [comment]
Here: https://github.com/martinet101/ElevenClock/pull/298

**Pull request merged**
