### PR TITLE
Fix english in all files

### PR DESCRIPTION
**Pull request by panther7**
ref: 9965f70

### CODE REVIEW

**Comment by martinet101** [comment]
No need, the strings were fixed in the english language file. 

Any errors/typos/etc, they can be fixed/chaged in the english language file, so no need to change every file

**Comment by panther7** [comment]
And what is wrong for fix it all?

**Comment by martinet101** [comment]
Nothing but unnecessary work

**Comment by panther7** [comment]
Copy & Paste & ReplaceAll is easy work :)

**Comment by martinet101** [comment]
Actually there's something wrong. I'll need to reimport all the files to Tolgee, the nes platform used for localising. So i'd prefer to update the language file only

**Comment by panther7** [comment]
But Tolgee translation project does not exists, or?

**Comment by martinet101** [comment]
Yes, it does. It is a new thing i introduced last week. On the Wiki there are the details.

**Comment by martinet101** [comment]
This is the actual reason for the switch from the .py to .json...

**Comment by martinet101** [comment]
You should be now in

**Comment by panther7** [comment]
Hm... I do not see anything...

**Comment by martinet101** [comment]
You should have received an email with a link on it. Open the invitation link to get access to the translation project

**Comment by panther7** [comment]
Ahhhh, it was spam, omg....

**Comment by panther7** [comment]
Translation done...

...but, only 99%, because i ca not translate too long text, error "max 200 chars"

**Comment by martinet101** [comment]
Mhmm... I'll try to fix that error...

**Comment by panther7** [comment]
Btw, could you add me to sk translation?

**Comment by panther7** [comment]
"Chat" moved to #803

/close

**Pull request closed without merging**
