### PR TITLE
Replace Argentinian flag with UAE flag

### PR DESCRIPTION
**Pull request by SapphireDisD**
The Argentinian flag is from a Spanish country, so it doesn't make much sense as Arabic. The United Arab Emirates are one of several Arab countries so I believe it should do better.

Though, there are several Arab countries, so maybe another flag could be used (or not one at all).

### CODE REVIEW

**Comment by SapphireDisD** [comment]
Is the contributor(s) from a specific country? Using their flag could also be a way to honour them.

**Comment by martinet101** [comment]
> Is the contributor(s) from a specific country

I am not understanding the question.

**Comment by martinet101** [comment]
This must not be changed here, but rather in the lang generator. I'm gonna close this PR and do this change.

**Comment by SapphireDisD** [comment]
Oh, all right!
Sorry about this.

**Comment by SapphireDisD** [comment]
And that terrible worded question meant using the translator's country flag instead of just a random one.

**Comment by martinet101** [comment]
Ah, didn't thought about it. 

In general, the flag is gotten from the _source_ country of the language. For example, _spanish_ from spain, etc. However, what you say i'd prefer not to do it, since some translations have 2+ translators, and i guess it's every translator decision to show their username or not in the credits section.

**Comment by SapphireDisD** [comment]
Arabic has a big history to get a "source country".

**Comment by martinet101** [comment]
changes will be reflected on next language update, hopefully soon.

**Comment by SapphireDisD** [comment]
Thank you a lot!

**Comment by martinet101** [comment]
What flag do you suggest for arabic? it must be available on that flag cdn server

**Comment by SapphireDisD** [comment]
I originally suggested UAE but the KSA is pretty important. I'll check if it's available.

**Comment by SapphireDisD** [comment]
Seems to be there https://flagcdn.com/sa.svg
Egypt could also be a good option.

**Pull request closed without merging**
