### PR TITLE
Update Czech translation to v3.4.0

### PR DESCRIPTION
**Pull request by panther7**

### CODE REVIEW

**Comment by martinet101** [comment]
New lang files available

**Comment by martinet101** [comment]
New strings are available

**Comment by panther7** [comment]
I found bug, after reboot app (clock), in settings sets always first value to "Show calendar".

**Review by martinet101 — APPROVED** [review]

**Comment by martinet101** [comment]
Ok, i'll take a look

**Comment by martinet101** [comment]
> I found bug, after reboot app (clock), in settings sets always first value to "Show calendar".

fixed

**Pull request merged**
