### PR TITLE
ShowDesktop button rewrite drawned line

### PR DESCRIPTION
**Pull request by panther7**
Now support light/dark mode correctly.

### CODE REVIEW

**Comment by panther7** [comment]
Fuck it... margin is not hoverable... 

I rewrite to change "property class", but it is to much slowly, and i dont know, maybe "signals" is slow?

**Comment by martinet101** [comment]
I also tried to implement the button in pure CSS, but it resulted impossible for me. 

mousePressEvent and any other related mouse events do not work if the button is completely transparent. They need an 1% opacity background to work. I'll check your commits and let you know

**Comment by martinet101** [comment]
I tried fixing css btn but it was impossible

I've remade the button with correct-sized and correct-color images, and added compatibility for the left-sided clock. 

You can check the changes on the latest head.

**Comment by panther7** [comment]
Ok, i dont like duplicate code and images (showdesktop_***) 🙈

New commits rewrite this to QPixman and works fine :)

Btw, next steps:
- add tooltip "Show desktop"
- increase space between clock and line  

   | Windows | ElevenCLock |
   | - | - |
   |  |  |

**Review by martinet101 — APPROVED** [review]

**Pull request merged**
