### PR TITLE
Improve dblClick on the clock

### PR DESCRIPTION
**Pull request by panther7**
Actually doesn't work dblClick on the clock properly.

(Single)click is emited always before DblClick. I found solution with timers, but (i don't know why), is bug, than singleClick is emited (again) after click on contextmenu. Maybe some "Eleven clock restart"?

Inspired from: https://www.xingyulei.com/post/qt-detect-click/index.html  
Prepearation for: #951

### CODE REVIEW

**Comment by martinet101** [comment]
What is happening is that eventFilter is being called on every click regiestered in the app, regardlñess of if it was in a clock or in the settings window

**Comment by martinet101** [comment]
I'll fix that

**Comment by martinet101** [comment]
> (Single)click is emited always before DblClick. I found solution with timers, but (i don't know why), is bug, than singleClick is emited (again) after click on contextmenu. Maybe some "Eleven clock restart"?

What is happening is that on this lapse of 250ms, the action center gets hidden by the click, but then it gets shown again by ElevenClock

**Comment by martinet101** [comment]
The bug is fixed by lowering the timeout, can you please test the head and see if it works for you?

**Comment by panther7** [comment]
Tomorrow

**Comment by panther7** [comment]
Done, 150ms is too short, 250ms is optimal for dbl click

Plus, i add two next commits.

**Review by martinet101 — DISMISSED** [review]

**Comment by martinet101** [comment]
Yep, but 250ms breaks the Win+n button on second click. 

If you click the clock, the notifs menu will open, but with 250ms, when clicking it again, the pane will hide and show again. With 150ms it does not

**Review by martinet101 — APPROVED** [review]

**Comment by panther7** [comment]
Sorry, but 150ms is too short for detect dblclick.

**Comment by martinet101** [comment]
I'll add a switch, but with 250ms the notification pane gets broken (at least for me, doesn't it happen on your machine?)

**Pull request merged**
